### ISSUE TITLE
Need proper license files

### ISSUE THREAD

**Issue by opoplawski** [ejmahler/strength_reduce#8]
Please provide proper license files in the repository.  In particular we need to know the copyright holder.  This is causing some issues with Fedora packaging (see https://bugzilla.redhat.com/show_bug.cgi?id=2116087).  Thanks.

**Comment by ejmahler** [comment]
Fixed in release 0.2.4. Thanks for bringing this up, and sorry for the long response.

**Comment by opoplawski** [comment]
Thanks for addressing it.
